import { FIELD_TYPE, SOURCE_TYPE, CONFIRM_LEVEL, AI_RISK } from './shared';

/** 来源 A 示例选项 */
export const SOURCE_A_OPTIONS = [
  { value: 'trade', label: '交易' },
  { value: 'inherit', label: '继承' },
  { value: 'gift', label: '赠与' },
  { value: 'other', label: '其他' },
];

/** 来源 B 示例选项 */
export const SOURCE_B_OPTIONS = [
  { value: 'domestic', label: '境内' },
  { value: 'overseas', label: '境外' },
];

/** 保税状态 */
export const BONDED_STATUS_OPTIONS = [
  { value: 'no', label: '否' },
  { value: 'shanghaiEntry', label: '是-上海入境' },
  { value: 'bondedEntry', label: '是-保税入境地' },
];

/**
 * 拍品表格列 — schema 驱动 LotTable / LotCellRenderer
 */
export const lotColumnsSchema = {
  id: 'lotColumns',
  version: '0.2.0',
  showSelectionColumn: true,
  showRowIndexColumn: true,
  showAuditStatusColumn: true,

  columns: [
    {
      key: 'selected',
      label: '',
      width: '40px',
      type: FIELD_TYPE.ACTION,
      required: false,
      editable: true,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.MANUAL_CONFIRM,
      confirmLevel: CONFIRM_LEVEL.AUTO_FILL,
      aiRisk: AI_RISK.NORMAL,
    },
    {
      key: 'rowIndex',
      label: '序号',
      width: '56px',
      type: FIELD_TYPE.NUMBER,
      required: false,
      editable: false,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.SYSTEM_DEFAULT,
      confirmLevel: CONFIRM_LEVEL.AUTO_FILL,
      aiRisk: AI_RISK.NORMAL,
    },
    {
      key: 'contractNo',
      label: '合同编号',
      width: '120px',
      type: FIELD_TYPE.TEXT,
      required: true,
      editable: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.AI_MATCHED,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
      aiRisk: AI_RISK.HIGH_RISK,
      description:
        'Demo：多合同批量导入时锁定归属；无法匹配主合同表格编号时为 conflict/missing',
    },
    {
      key: 'lotContractNo',
      label: '拍品合同编号',
      width: '120px',
      type: FIELD_TYPE.TEXT,
      required: false,
      editable: true,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.SYSTEM_DEFAULT,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      aiRisk: AI_RISK.LOW_CONFIDENCE,
      inlineActions: ['copy', 'edit'],
    },
    {
      key: 'authorEra',
      label: '作者/年代',
      width: '100px',
      type: FIELD_TYPE.TEXT,
      required: false,
      editable: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_LOT_LIST,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      aiRisk: AI_RISK.NORMAL,
    },
    {
      key: 'lotName',
      label: '拍品名',
      width: 'minmax(120px, 1.2fr)',
      type: FIELD_TYPE.TEXT,
      required: true,
      editable: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_LOT_LIST,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
      aiRisk: AI_RISK.NORMAL,
    },
    {
      key: 'texture',
      label: '质地',
      width: '80px',
      type: FIELD_TYPE.SELECT,
      required: false,
      editable: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_LOT_LIST,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      aiRisk: AI_RISK.NORMAL,
      options: [
        { value: 'porcelain', label: '瓷' },
        { value: 'jade', label: '玉' },
        { value: 'painting', label: '书画' },
      ],
    },
    {
      key: 'form',
      label: '形式',
      width: '100px',
      type: FIELD_TYPE.TEXTAREA,
      required: false,
      editable: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_LOT_LIST,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      aiRisk: AI_RISK.NORMAL,
    },
    {
      key: 'dimensions',
      label: '尺寸 (cm)',
      width: '140px',
      type: FIELD_TYPE.DIMENSION,
      required: false,
      editable: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_LOT_LIST,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      aiRisk: AI_RISK.LOW_CONFIDENCE,
      subFields: ['length', 'width', 'height'],
    },
    {
      key: 'condition',
      label: '包装及品相现状',
      width: '120px',
      type: FIELD_TYPE.TEXTAREA,
      required: false,
      editable: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_LOT_LIST,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      aiRisk: AI_RISK.NORMAL,
    },
    {
      key: 'insurancePrice',
      label: '保险价(RMB)',
      width: '100px',
      type: FIELD_TYPE.MONEY,
      required: true,
      editable: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_LOT_LIST,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
      aiRisk: AI_RISK.HIGH_RISK,
    },
    {
      key: 'reservePrice',
      label: '保留价(RMB)',
      width: '100px',
      type: FIELD_TYPE.MONEY,
      required: true,
      editable: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_LOT_LIST,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
      aiRisk: AI_RISK.HIGH_RISK,
      description: '底价/保留价，页面统一展示文案',
    },
    {
      key: 'storagePrice',
      label: '保管价(RMB)',
      width: '100px',
      type: FIELD_TYPE.MONEY,
      required: false,
      editable: true,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.RULE_CONFIG,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      aiRisk: AI_RISK.NORMAL,
    },
    {
      key: 'sourceA',
      label: '来源A',
      width: '88px',
      type: FIELD_TYPE.SELECT,
      required: true,
      editable: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.DICTIONARY_SELECT,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      aiRisk: AI_RISK.NORMAL,
      options: SOURCE_A_OPTIONS,
    },
    {
      key: 'sourceB',
      label: '来源B',
      width: '88px',
      type: FIELD_TYPE.SELECT,
      required: true,
      editable: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.DICTIONARY_SELECT,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      aiRisk: AI_RISK.NORMAL,
      options: SOURCE_B_OPTIONS,
    },
    {
      key: 'lotType',
      label: '拍品类型',
      width: '88px',
      type: FIELD_TYPE.SELECT,
      required: true,
      editable: true,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.DICTIONARY_SELECT,
      confirmLevel: CONFIRM_LEVEL.AUTO_FILL,
      aiRisk: AI_RISK.NORMAL,
      options: [
        { value: 'lot', label: '拍品' },
        { value: 'collection', label: '藏品' },
      ],
    },
    {
      key: 'consignorBackground',
      label: '委托方背景及留存',
      width: '120px',
      type: FIELD_TYPE.TEXTAREA,
      required: false,
      editable: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_LOT_LIST,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      aiRisk: AI_RISK.NORMAL,
    },
    {
      key: 'bondedStatus',
      label: '保税状态',
      width: '120px',
      type: FIELD_TYPE.SELECT,
      required: true,
      editable: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_LOT_LIST,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
      aiRisk: AI_RISK.HIGH_RISK,
      options: BONDED_STATUS_OPTIONS,
    },
    {
      key: 'plannedAuctionPeriod',
      label: '预上拍时期',
      width: '100px',
      type: FIELD_TYPE.SELECT,
      required: true,
      editable: true,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.DICTIONARY_SELECT,
      confirmLevel: CONFIRM_LEVEL.AUTO_FILL,
      aiRisk: AI_RISK.NORMAL,
      options: [
        { value: '2025spring', label: '2025春季' },
        { value: '2025autumn', label: '2025秋季' },
      ],
    },
    {
      key: 'coverRemarks',
      label: '拍品封面备注',
      width: '100px',
      type: FIELD_TYPE.TEXTAREA,
      required: false,
      editable: true,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.MANUAL_CONFIRM,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      aiRisk: AI_RISK.NORMAL,
      uncertain: true,
    },
    {
      key: 'auditStatus',
      label: '拍品状态',
      width: '100px',
      type: FIELD_TYPE.STATUS,
      required: false,
      editable: false,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.AUDIT_STATUS,
      confirmLevel: CONFIRM_LEVEL.AUTO_FILL,
      aiRisk: AI_RISK.NORMAL,
    },
  ],
};

export function getLotColumn(key) {
  return lotColumnsSchema.columns.find((c) => c.key === key);
}

export function getEditableLotColumns() {
  return lotColumnsSchema.columns.filter(
    (c) => c.editable && c.type !== FIELD_TYPE.ACTION && c.type !== FIELD_TYPE.STATUS
  );
}
