import { FIELD_TYPE, SOURCE_TYPE, CONFIRM_LEVEL, CONSIGNOR_TYPE } from './shared';

/**
 * 主合同页 schema — 基本信息 / 委托人 / 合同照片
 * 合同内容区见 contractContentSchema.js
 */
export const mainContractSchema = {
  id: 'mainContract',
  label: '主合同',
  version: '0.1.0',
  pageId: 'P04',

  sections: [
    { key: 'basicInfo', label: '基本信息', order: 1, layout: 'grid-2' },
    { key: 'consignorInfo', label: '委托人信息', order: 2, layout: 'grid-2' },
    {
      key: 'contractContent',
      label: '合同内容',
      order: 3,
      layout: 'custom',
      schemaRef: 'contractContentSchema',
    },
    { key: 'contractPhotos', label: '合同照片', order: 4, layout: 'full' },
  ],

  fields: [
    // —— 基本信息（以真实系统为准）——
    {
      key: 'contractType',
      label: '合同类型',
      section: 'basicInfo',
      type: FIELD_TYPE.SELECT,
      required: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
      options: [
        { value: 'consignment', label: '委托拍卖合同' },
        { value: 'other', label: '其他' },
      ],
    },
    {
      key: 'contractNo',
      label: '合同编号',
      section: 'basicInfo',
      type: FIELD_TYPE.TEXT,
      required: true,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.SYSTEM_DEFAULT,
      confirmLevel: CONFIRM_LEVEL.AUTO_FILL,
      placeholder: '自动生成',
    },
    {
      key: 'signStatus',
      label: '签署状态',
      section: 'basicInfo',
      type: FIELD_TYPE.SELECT,
      required: false,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.SYSTEM_DEFAULT,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      options: [
        { value: 'unsigned', label: '未签署' },
        { value: 'signed', label: '已签署' },
      ],
    },
    {
      key: 'department',
      label: '部门',
      section: 'basicInfo',
      type: FIELD_TYPE.SELECT,
      required: false,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.SYSTEM_DEFAULT,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      options: [
        { value: 'dep-01', label: '书画部' },
        { value: 'dep-02', label: '瓷器部' },
      ],
    },
    {
      key: 'handler',
      label: '经办人',
      section: 'basicInfo',
      type: FIELD_TYPE.SELECT,
      required: false,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.SYSTEM_DEFAULT,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      options: [
        { value: 'user-wang', label: '王某某' },
        { value: 'user-li', label: '李某某' },
      ],
    },
    {
      key: 'agent',
      label: '代办人',
      section: 'basicInfo',
      type: FIELD_TYPE.SELECT,
      required: false,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.SYSTEM_DEFAULT,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      options: [
        { value: 'agent-01', label: '代办人 A' },
        { value: 'agent-02', label: '代办人 B' },
      ],
    },
    {
      key: 'currency',
      label: '币种',
      section: 'basicInfo',
      type: FIELD_TYPE.SELECT,
      required: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      options: [
        { value: 'CNY', label: '人民币' },
        { value: 'USD', label: '美元' },
        { value: 'HKD', label: '港币' },
      ],
    },
    {
      key: 'taxRate',
      label: '税率',
      section: 'basicInfo',
      type: FIELD_TYPE.TEXT,
      required: false,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      placeholder: '如 6%',
    },
    {
      key: 'standardCatalog',
      label: '普通图录',
      section: 'basicInfo',
      type: FIELD_TYPE.SELECT,
      required: false,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.RULE_CONFIG,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      options: [
        { value: 'standard', label: '标准图录' },
        { value: 'premium', label: '精品图录' },
      ],
    },

    // —— 委托人类型（控制 visibleWhen）——
    {
      key: 'consignorType',
      label: '委托人类型',
      section: 'consignorInfo',
      type: FIELD_TYPE.SELECT,
      required: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
      options: [
        { value: CONSIGNOR_TYPE.PERSONAL, label: '个人委托人' },
        { value: CONSIGNOR_TYPE.ORGANIZATION, label: '机构委托人' },
      ],
      defaultValue: CONSIGNOR_TYPE.PERSONAL,
    },

    // —— 个人委托人字段 ——
    {
      key: 'consignorName',
      label: '委托人',
      section: 'consignorInfo',
      type: FIELD_TYPE.TEXT,
      required: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
      visibleWhen: { consignorType: CONSIGNOR_TYPE.PERSONAL },
    },
    {
      key: 'idType',
      label: '证件类型',
      section: 'consignorInfo',
      type: FIELD_TYPE.SELECT,
      required: false,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      visibleWhen: { consignorType: CONSIGNOR_TYPE.PERSONAL },
      options: [
        { value: 'idCard', label: '身份证' },
        { value: 'passport', label: '护照' },
        { value: 'other', label: '其他' },
      ],
    },
    {
      key: 'idNumber',
      label: '证件号码',
      section: 'consignorInfo',
      type: FIELD_TYPE.TEXT,
      required: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
      visibleWhen: { consignorType: CONSIGNOR_TYPE.PERSONAL },
    },
    {
      key: 'dateOfBirth',
      label: '出生日期',
      section: 'consignorInfo',
      type: FIELD_TYPE.DATE,
      required: false,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      visibleWhen: { consignorType: CONSIGNOR_TYPE.PERSONAL },
    },
    {
      key: 'gender',
      label: '性别',
      section: 'consignorInfo',
      type: FIELD_TYPE.SELECT,
      required: false,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      visibleWhen: { consignorType: CONSIGNOR_TYPE.PERSONAL },
      options: [
        { value: 'male', label: '男' },
        { value: 'female', label: '女' },
      ],
    },
    {
      key: 'mobilePhone',
      label: '联系电话',
      section: 'consignorInfo',
      type: FIELD_TYPE.TEXT,
      required: false,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
      visibleWhen: { consignorType: CONSIGNOR_TYPE.PERSONAL },
    },
    {
      key: 'address',
      label: '地址',
      section: 'consignorInfo',
      type: FIELD_TYPE.ADDRESS,
      required: false,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
      visibleWhen: { consignorType: CONSIGNOR_TYPE.PERSONAL },
    },
    {
      key: 'zipCode',
      label: '邮编',
      section: 'consignorInfo',
      type: FIELD_TYPE.TEXT,
      required: false,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      visibleWhen: { consignorType: CONSIGNOR_TYPE.PERSONAL },
    },
    {
      key: 'idPhotos',
      label: '证件照片',
      section: 'consignorInfo',
      type: FIELD_TYPE.IMAGE_UPLOAD,
      required: false,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.MANUAL_CONFIRM,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
      visibleWhen: { consignorType: CONSIGNOR_TYPE.PERSONAL },
    },

    // —— 机构委托人（第一版预留，默认隐藏）——
    {
      key: 'orgName',
      label: '机构名称',
      section: 'consignorInfo',
      type: FIELD_TYPE.TEXT,
      required: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
      visibleWhen: { consignorType: CONSIGNOR_TYPE.ORGANIZATION },
      reserved: true,
    },
    {
      key: 'unifiedSocialCreditCode',
      label: '统一社会信用代码',
      section: 'consignorInfo',
      type: FIELD_TYPE.TEXT,
      required: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
      visibleWhen: { consignorType: CONSIGNOR_TYPE.ORGANIZATION },
      reserved: true,
    },
    {
      key: 'legalRepresentative',
      label: '法定代表人',
      section: 'consignorInfo',
      type: FIELD_TYPE.TEXT,
      required: false,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      visibleWhen: { consignorType: CONSIGNOR_TYPE.ORGANIZATION },
      reserved: true,
    },
    {
      key: 'orgAddress',
      label: '机构地址',
      section: 'consignorInfo',
      type: FIELD_TYPE.ADDRESS,
      required: false,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
      visibleWhen: { consignorType: CONSIGNOR_TYPE.ORGANIZATION },
      reserved: true,
    },
    {
      key: 'orgContactPerson',
      label: '联系人',
      section: 'consignorInfo',
      type: FIELD_TYPE.TEXT,
      required: false,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
      visibleWhen: { consignorType: CONSIGNOR_TYPE.ORGANIZATION },
      reserved: true,
    },

    // —— 个人 / 机构共用银行信息 ——
    {
      key: 'bankAccountName',
      label: '收款人全称',
      section: 'consignorInfo',
      type: FIELD_TYPE.TEXT,
      required: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
    },
    {
      key: 'bankAccountNo',
      label: '银行账号',
      section: 'consignorInfo',
      type: FIELD_TYPE.TEXT,
      required: true,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
    },
    {
      key: 'bankName',
      label: '开户行',
      section: 'consignorInfo',
      type: FIELD_TYPE.TEXT,
      required: false,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
    },
    {
      key: 'bankBranch',
      label: '开户支行',
      section: 'consignorInfo',
      type: FIELD_TYPE.TEXT,
      required: false,
      aiExtractable: true,
      sourceType: SOURCE_TYPE.PAPER_CONTRACT,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
    },
    {
      key: 'consignorRemarks',
      label: '备注',
      section: 'consignorInfo',
      type: FIELD_TYPE.TEXTAREA,
      required: false,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.MANUAL_CONFIRM,
      confirmLevel: CONFIRM_LEVEL.NEED_CONFIRM,
    },

    // —— 合同照片 ——
    {
      key: 'contractScans',
      label: '合同照片',
      section: 'contractPhotos',
      type: FIELD_TYPE.ATTACHMENT,
      required: false,
      aiExtractable: false,
      sourceType: SOURCE_TYPE.MANUAL_CONFIRM,
      confirmLevel: CONFIRM_LEVEL.MUST_CONFIRM,
    },
  ],
};

/** 按 section 分组字段 */
export function getFieldsBySection(sectionKey) {
  return mainContractSchema.fields.filter((f) => f.section === sectionKey);
}

export function getFieldDef(key) {
  return mainContractSchema.fields.find((f) => f.key === key);
}
